### ISSUE TITLE
Accept property keys that don't start with `--`

### ISSUE THREAD

**Issue by danbahrami** [danbahrami/react-custom-properties#4]
At the moment a warning is shown if you try to add a custom property that doesn't begin with `--`.

For example...

```
// valid
<CustomProperties properties={{ '--brand-color': '#888' }} />

// invalid
<CustomProperties properties={{ brand-color: '#888' }} />
```

For these invalid cases, it might be nicer to make them valid by prepending the `--` internally.

**Comment by gtournie** [comment]
@danbahrami Not sure it's a good idea. The double dash removes some confusion between a css prop and a css var. In your example it's even more confusing as your var is named after a css prop. 

It would be probably more relevant to have something like:
```
<CustomProperties variables={{ 'my-color': '#888' }} />
```

**Comment by danbahrami** [comment]
Closing this issue due to the reason mentioned by @gtournie
